#!/usr/bin/env python3
"""Regenerate Glimmer/Stream/HIDGamepad/GameControllerDB+Data.swift from SDL_GameControllerDB.

Usage: scripts/gen-gamecontrollerdb.py [path-or-URL to gamecontrollerdb.txt]
Defaults to the upstream master file. Only the "Mac OS X" section is kept.
"""
import pathlib
import sys
import urllib.request

UPSTREAM = "https://raw.githubusercontent.com/mdqinc/SDL_GameControllerDB/master/gamecontrollerdb.txt"
OUT = pathlib.Path(__file__).resolve().parent.parent / "Glimmer/Stream/HIDGamepad/GameControllerDB+Data.swift"


def load(source: str) -> str:
    if source.startswith("http"):
        with urllib.request.urlopen(source) as response:  # noqa: S310 - fixed upstream URL
            return response.read().decode("utf-8")
    return pathlib.Path(source).read_text()


def macos_entries(text: str) -> list[str]:
    entries, inside = [], False
    for line in text.splitlines():
        if line.startswith("# Mac OS X"):
            inside = True
            continue
        if line.startswith("# ") and inside:
            break
        if inside and line.strip() and not line.startswith("#"):
            entries.append(line.strip())
    return entries


def main() -> None:
    source = sys.argv[1] if len(sys.argv) > 1 else UPSTREAM
    entries = macos_entries(load(source))
    if not entries:
        sys.exit("no Mac OS X entries found")
    lines = [
        "//",
        "//  GameControllerDB+Data.swift",
        "//",
        "//  The macOS section of SDL_GameControllerDB (zlib licence, see CREDITS.md),",
        "//  generated by scripts/gen-gamecontrollerdb.py. Do not edit by hand.",
        "//",
        "// swiftlint:disable line_length",
        "",
        "extension GameControllerDB {",
        f"    /// {len(entries)} SDL2-format mapping lines for platform Mac OS X.",
        "    static let macOSEntries: [String] = [",
    ]
    for index, entry in enumerate(entries):
        if '"' in entry or "\\" in entry:
            sys.exit(f"unexpected quote or backslash in entry: {entry}")
        lines.append(f'        "{entry}"' + ("," if index < len(entries) - 1 else ""))
    lines += ["    ]", "}", "// swiftlint:enable line_length", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(OUT.parents[3])} with {len(entries)} entries")


if __name__ == "__main__":
    main()
