#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2026 ugfugl.io

# Stamp the source commit and its time into telemetry, so a clean build is a pure
# function of the commit (reproducible). Dirty builds stamp the wall clock instead.
# Generated output is ignored by git and contains no credentials.

set -euo pipefail

# Resolve repo root from this script's location so it works regardless of CWD.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$REPO_ROOT/Glimmer/BuildInfo.generated.swift"

commit="unknown"
dirty=0
if git -C "$REPO_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
    commit="$(git -C "$REPO_ROOT" rev-parse --short=12 HEAD 2>/dev/null || echo unknown)"
    # Flag a dirty worktree so a metric can never claim a clean build it wasn't.
    if ! git -C "$REPO_ROOT" diff --quiet HEAD 2>/dev/null \
        || [ -n "$(git -C "$REPO_ROOT" ls-files --others --exclude-standard)" ]; then
        commit="${commit}-dirty"
        dirty=1
    fi
fi

# Clean checkouts use the commit time (or SOURCE_DATE_EPOCH); dirty ones stay distinguishable.
epoch="${SOURCE_DATE_EPOCH:-}"
if [ "$dirty" = 0 ] && [ "$commit" != unknown ]; then
    epoch="${epoch:-$(git -C "$REPO_ROOT" log -1 --format=%ct HEAD)}"
fi
build_date="$(date -u -r "${epoch:-$(date +%s)}" +%Y-%m-%dT%H:%M:%SZ)"

contents="$(cat <<EOF
//
//  BuildInfo.generated.swift
//
//  GENERATED by scripts/generate-build-info.sh; do not edit.
//  Source attribution for local diagnostics.

enum BuildInfo {
    /// Short git HEAD (12 hex) at build time, "-dirty" when the worktree had
    /// uncommitted changes, or "unknown" outside a git checkout.
    static let commit = "$commit"
    /// UTC ISO8601 stamp: the commit time for a clean checkout, otherwise the build time.
    static let date = "$build_date"
}
EOF
)"

# Clean commits are immutable; dirty sources can change without changing their SHA.
# Refresh dirty timestamps so different local builds remain distinguishable in telemetry.
if [ "$dirty" = 0 ] && [ "$commit" != unknown ] && [ -f "$OUT" ] && grep -q "static let commit = \"$commit\"" "$OUT"; then
    exit 0
fi

printf '%s\n' "$contents" > "$OUT"
echo "  ✓ BuildInfo.generated.swift → commit=$commit"
